# Activate database
use zomatodb;

# Showing tables
show tables;

# tables 
select * from customer; -- Customer_id, Customer_name, Contact_number, Address
select * from foods; -- food_id, food_name, price_per_unit
select * from Order_detail; -- Order_id, Customer_id, restaurent_id, Employee_id, order_status, order_time, delivered_time
select * from order_food; -- OrderF_id, order_id, Customer_id, restaurant_id, food_id, quantity, employee_id
select * from payment_table; -- transaction_id. order_id, payment_type, payment_status
select * from restaurant; -- restaurant_id, restaurant_name, rloaction, rrating
select * from zomato_employee; -- employee_id, employee_name, emp_contact_number, employee_avg_rating
# QUERIES 

-- 1. List the top 3 customers who have placed the highest number of orders.
SELECT customer_id, COUNT(*) AS total_orders
FROM order_detail
GROUP BY customer_id
ORDER BY total_orders DESC
LIMIT 3;

-- 2. Find the restaurant that has received the highest average rating.
select restaurant_id, restaurant_name, rlocation,
avg(rrating) as avg_rating
from restaurant
group by restaurant_id
order by avg_rating desc
limit 1;

-- 3. List all orders from order_detail that were delivered in under 30 minutes. 
SELECT *
FROM order_detail
WHERE TIMESTAMPDIFF(MINUTE, order_time, delivered_time) < 30;

/* 4. Calculate the total revenue generated by each food item. Display food_id, food_name 
and Total revenue ordered by total revenue in descending order.
*/
select o_f.food_id, f.food_name,
sum(f.price_per_unit * o_f.quantity) as Total_revenue 
from foods as f
join order_food as o_f
on f.food_id = o_f.food_id
group by 1
order by  total_revenue desc;

-- 5. Find the second highest revenue-generating restaurant. 
select r.restaurant_id, r.restaurant_name,
sum(ofd.quantity * f.price_per_unit) as total_revenue
from 
restaurant as r
join order_food as ofd
on r.restaurant_id = ofd.restaurant_id
join foods as f
on ofd.food_id = f.food_id
group by 1
order by total_revenue desc
limit 1 offset 1;

-- 6. Find the 5 most popular food items based on the quantity sold. 
select f.Food_id, f.Food_name,
sum(ofd.quantity) as Total_Quantity
from 
foods as f
join order_food as ofd
on f.food_id = ofd.food_id
group by f.food_id, f.food_name
order by Total_Quantity desc
limit 5;

-- 7. List the top 3 Zomato employees with the highest average delivery ratings. 
select employee_id, max(employee_avg_rating) as Highest_avg_del_rating
from zomato_employee
group by 1
order by Highest_avg_del_rating desc 
limit 3;

-- 8. Determine the month with the highest number of total orders placed. 
select month(delivered_time) As Month_Name,
count(month(delivered_time)) As Total_Orders from order_detail
group by 1
limit 1;

/* 9. Calculate the average order amount for each customer. Order by average order amount 
in descending order. */
select 
	Customer_id,
	avg(order_Amount) as Avg_order_Amount
from
    (
		select
		ofd.order_id, 
		ofd.customer_id,
		sum(ofd.quantity * f.price_per_unit) as Order_Amount
from order_food as ofd
join foods as f
	on ofd.food_id = f.food_id
	group by ofd.order_id, ofd.customer_id
) as Customer_Orders
group by customer_id
order By Avg_Order_Amount Desc;

-- 10. Identify the most frequent customer for each restaurant. 
select 
distinct(r.restaurant_name) as Restaurant_name, 
count(od.Customer_id) as Most_frequent_customer
from Order_detail as od
join restaurant as r
on od.restaurant_id = r.restaurant_id
group by 1
order by Most_frequent_customer Desc ;

-- 11. Calculate the total number of orders placed on weekends. 
select count(order_id) as Total_Weekend_Orders
from Order_detail
where dayname(order_time) in ('Saturday', 'Sunday');

/*
12. Calculate the average delivery time (in minutes) for orders placed on weekdays versus 
weekends. */
select
	case
		when dayname(order_time) in ('Saturday', 'Sunday')
        then 'Weekend'
        else 'Weekday'
        end as Day_Type,
	avg(timestampdiff(minute, order_time, delivered_time)) as Avg_Delivery_Time
    from order_detail
    group by Day_type;
    
/* 
13. List the top 5 most expensive food items. Display food_id, food_name, and 
price_per_unit for all food items with the highest 5 prices.*/
SELECT
    food_id,
    food_name,
    price_per_unit
FROM foods
ORDER BY price_per_unit DESC
LIMIT 5;

-- 14. Find the restaurant with the most diverse menu (i.e., the highest number of food items).
SELECT
    r.restaurant_id,
    r.restaurant_name,
    COUNT(DISTINCT ofd.food_id) AS total_food_items
FROM restaurant AS r
JOIN order_food AS ofd
ON r.restaurant_id = ofd.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
ORDER BY total_food_items DESC
LIMIT 1;

-- 15. Calculate total payment amount for each payment type.
SELECT
    pt.payment_type,
    SUM(ofd.quantity * f.price_per_unit) AS total_payment_amount
FROM payment_table AS pt
JOIN order_food AS ofd
    ON pt.order_id = ofd.order_id
JOIN foods AS f
    ON ofd.food_id = f.food_id
GROUP BY pt.payment_type;







